// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logBF_summary_cpp
double logBF_summary_cpp(const arma::vec& XtY, const arma::mat& XtX, double YtY, const arma::vec& sigma_vec, const arma::uvec& gamma_idx, int n);
RcppExport SEXP _MRBMA_logBF_summary_cpp(SEXP XtYSEXP, SEXP XtXSEXP, SEXP YtYSEXP, SEXP sigma_vecSEXP, SEXP gamma_idxSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type XtY(XtYSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< double >::type YtY(YtYSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_vec(sigma_vecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type gamma_idx(gamma_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(logBF_summary_cpp(XtY, XtX, YtY, sigma_vec, gamma_idx, n));
    return rcpp_result_gen;
END_RCPP
}
// beta_summary_cpp
arma::vec beta_summary_cpp(const arma::vec& XtY, const arma::mat& XtX, const arma::vec& sigma_vec, const arma::uvec& gamma_idx, int d_Exposure);
RcppExport SEXP _MRBMA_beta_summary_cpp(SEXP XtYSEXP, SEXP XtXSEXP, SEXP sigma_vecSEXP, SEXP gamma_idxSEXP, SEXP d_ExposureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type XtY(XtYSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_vec(sigma_vecSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type gamma_idx(gamma_idxSEXP);
    Rcpp::traits::input_parameter< int >::type d_Exposure(d_ExposureSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_summary_cpp(XtY, XtX, sigma_vec, gamma_idx, d_Exposure));
    return rcpp_result_gen;
END_RCPP
}
// cooksD_cpp
Rcpp::List cooksD_cpp(const arma::vec& y, const arma::mat& x, const arma::vec& sigma_vec);
RcppExport SEXP _MRBMA_cooksD_cpp(SEXP ySEXP, SEXP xSEXP, SEXP sigma_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_vec(sigma_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(cooksD_cpp(y, x, sigma_vec));
    return rcpp_result_gen;
END_RCPP
}
// exhaustive_bf_cpp
Rcpp::List exhaustive_bf_cpp(const arma::vec& XtY, const arma::mat& XtX, double YtY, const arma::vec& sigma_vec, int d_Exposure, int n_SNPs, double prior_prob);
RcppExport SEXP _MRBMA_exhaustive_bf_cpp(SEXP XtYSEXP, SEXP XtXSEXP, SEXP YtYSEXP, SEXP sigma_vecSEXP, SEXP d_ExposureSEXP, SEXP n_SNPsSEXP, SEXP prior_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type XtY(XtYSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< double >::type YtY(YtYSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_vec(sigma_vecSEXP);
    Rcpp::traits::input_parameter< int >::type d_Exposure(d_ExposureSEXP);
    Rcpp::traits::input_parameter< int >::type n_SNPs(n_SNPsSEXP);
    Rcpp::traits::input_parameter< double >::type prior_prob(prior_probSEXP);
    rcpp_result_gen = Rcpp::wrap(exhaustive_bf_cpp(XtY, XtX, YtY, sigma_vec, d_Exposure, n_SNPs, prior_prob));
    return rcpp_result_gen;
END_RCPP
}
// sss_core_cpp
Rcpp::List sss_core_cpp(const arma::vec& XtY, const arma::mat& XtX, double YtY, const arma::vec& sigma_vec, int d_Exposure, int n_SNPs, double prior_prob, int kmin, int kmax, int max_iter, bool verbose);
RcppExport SEXP _MRBMA_sss_core_cpp(SEXP XtYSEXP, SEXP XtXSEXP, SEXP YtYSEXP, SEXP sigma_vecSEXP, SEXP d_ExposureSEXP, SEXP n_SNPsSEXP, SEXP prior_probSEXP, SEXP kminSEXP, SEXP kmaxSEXP, SEXP max_iterSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type XtY(XtYSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< double >::type YtY(YtYSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_vec(sigma_vecSEXP);
    Rcpp::traits::input_parameter< int >::type d_Exposure(d_ExposureSEXP);
    Rcpp::traits::input_parameter< int >::type n_SNPs(n_SNPsSEXP);
    Rcpp::traits::input_parameter< double >::type prior_prob(prior_probSEXP);
    Rcpp::traits::input_parameter< int >::type kmin(kminSEXP);
    Rcpp::traits::input_parameter< int >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sss_core_cpp(XtY, XtX, YtY, sigma_vec, d_Exposure, n_SNPs, prior_prob, kmin, kmax, max_iter, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MRBMA_logBF_summary_cpp", (DL_FUNC) &_MRBMA_logBF_summary_cpp, 6},
    {"_MRBMA_beta_summary_cpp", (DL_FUNC) &_MRBMA_beta_summary_cpp, 5},
    {"_MRBMA_cooksD_cpp", (DL_FUNC) &_MRBMA_cooksD_cpp, 3},
    {"_MRBMA_exhaustive_bf_cpp", (DL_FUNC) &_MRBMA_exhaustive_bf_cpp, 7},
    {"_MRBMA_sss_core_cpp", (DL_FUNC) &_MRBMA_sss_core_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_MRBMA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
