# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute log10 Bayes Factor for a single model
#' @description Evaluates the log10 Bayes Factor (BF) for a model defined by the
#' indicator vector \code{gamma_idx} using pre-computed summary-level statistics \eqn{X^\top X}, \eqn{X^\top Y} and \eqn{Y^\top Y}. This
#' avoids re-multiplying the full data matrices for every model evaluation and is the innermost computational kernel called by
#' \code{exhaustive_bf_cpp} and \code{sss_core_cpp}.
#' Throughout, \eqn{d} denotes the number of exposures, \eqn{n} the number of SNPs.
#'
#' @param XtY       Numeric vector of length \eqn{d}. Pre-computed
#'                  \eqn{X^\top Y = \texttt{betaX}^\top \texttt{betaY}}
#' @param XtX       Numeric matrix of dimension \eqn{d \times d}. Pre-computed
#'                  \eqn{X^\top X = \texttt{betaX}^\top \texttt{betaX}}
#' @param YtY       Positive numeric scalar. Pre-computed
#'                  \eqn{Y^\top Y = \texttt{betaY}^\top \texttt{betaY}}
#' @param sigma_vec Numeric vector of length \eqn{d}. Prior standard
#'                  deviations for causal effects, one per exposure
#' @param gamma_idx Integer vector of column indices into betaX identifying the exposures in model \eqn{\gamma}
#' @param n         Positive integer. Number of SNPs (instruments) \eqn{n}
#'
#' @return Scalar double: log10 Bayes Factor (BF) for model \eqn{\gamma}. Returns
#' \code{-Inf} if the system is (near-)singular
#'
#' @export
logBF_summary_cpp <- function(XtY, XtX, YtY, sigma_vec, gamma_idx, n) {
    .Call(`_MRBMA_logBF_summary_cpp`, XtY, XtX, YtY, sigma_vec, gamma_idx, n)
}

#' @title Compute causal estimates for a single model (summary-data version)
#' @description Returns the posterior mean causal estimate vector for the
#' model \eqn{\gamma} defined by \code{gamma_idx} (column indices into betaX).
#' Estimates are computed from pre-computed summary-level statistics to avoid
#' recomputing matrix products. Exposures not in \eqn{\gamma} receive an estimate of zero.
#' Throughout, \eqn{d} denotes the number of exposures.
#'
#' @param XtY       Numeric vector of length \eqn{d}. Pre-computed
#'                  \eqn{X^\top Y}
#' @param XtX       Numeric matrix of dimension \eqn{d \times d}. Pre-computed
#'                  \eqn{X^\top X}
#' @param sigma_vec Numeric vector of length \eqn{d}. Prior standard
#'                  deviations for causal effects
#' @param gamma_idx Integer vector of column indices into betaX for model \eqn{\gamma}
#' @param d_Exposure Positive integer. Total number of exposures \eqn{d}
#'
#' @return Numeric vector of length \eqn{d}. Posterior mean causal estimates;
#' elements corresponding to exposures absent from \eqn{\gamma} are zero
#'
#' @export
beta_summary_cpp <- function(XtY, XtX, sigma_vec, gamma_idx, d_Exposure) {
    .Call(`_MRBMA_beta_summary_cpp`, XtY, XtX, sigma_vec, gamma_idx, d_Exposure)
}

#' @title Compute Cook's distance for a given MRBMA model
#' @description Computes Cook's distance of \insertCite{Cook1977;textual}{MRBMA}
#' for each SNP in model \eqn{\gamma} using a ridge-regularised hat matrix. The threshold is the 50th percentile of an \eqn{F(k, n -
#' k)} distribution, where \eqn{k = |\gamma|}
#'
#' @param y         Numeric vector of length \eqn{n}.
#'                  SNP-outcome association estimates (\code{betaY})
#' @param x         Numeric matrix of dimension \eqn{n \times |\gamma|}.
#'                  Submatrix of \code{betaX} restricted to exposures in \eqn{\gamma}
#' @param sigma_vec Numeric vector of length \eqn{|\gamma|}. Prior standard
#'                  deviations for the exposures in \eqn{\gamma}
#'
#' @return A named list:
#' \describe{
#'   \item{\code{cooksD}}{Numeric vector of length \eqn{n}:
#'         Cook's distance for each SNP}
#'   \item{\code{cooksD_thresh}}{Scalar double: suggested flagging threshold
#'         (\eqn{F_{0.5}(k, n-k)})}
#' }
#'
#' @references
#' \insertAllCited{}
#'
#' @export
cooksD_cpp <- function(y, x, sigma_vec) {
    .Call(`_MRBMA_cooksD_cpp`, y, x, sigma_vec)
}

#' @title Exhaustive BF search -- evaluate all \eqn{2^d - 1} sub-models in C++
#' @description Enumerates all combinations of exposures of size
#' \eqn{k = 1, \ldots, d} using a recursive combinatorial generator and computes the log10 Bayes Factor (BF), log10 binomial prior, and
#' causal estimate vector for each model. All matrix operations are performed via RcppArmadillo. This function is the computational
#' backend of \code{MRBMA_exhaustive}. For the BF derivation see \insertCite{Zuber2020;textual}{MRBMA}.
#' Throughout, \eqn{d} denotes the number of exposures, \eqn{n} the number of SNPs, and \eqn{k = |\gamma|} the model size.
#'
#' @param XtY       Numeric vector of length \eqn{d}. Pre-computed
#'                  \eqn{X^\top Y}
#' @param XtX       Numeric matrix of dimension \eqn{d \times d}. Pre-computed
#'                  \eqn{X^\top X}
#' @param YtY       Positive numeric scalar. Pre-computed \eqn{Y^\top Y}
#' @param sigma_vec Numeric vector of length \eqn{d}. Prior standard
#'                  deviations
#' @param d_Exposure Positive integer. Number of exposures \eqn{d}
#' @param n_SNPs    Positive integer. Number of SNPs (instruments) \eqn{n}
#' @param prior_prob Numeric scalar in \eqn{(0, 1)}. Prior inclusion
#'                  probability per exposure
#'
#' @return A named list:
#' \describe{
#'   \item{\code{keys}}{Character vector of model keys (comma-separated
#'         column indices into betaX), length \eqn{2^d - 1}}
#'   \item{\code{logBF}}{Numeric vector of log10 Bayes Factors (BFs), same length}
#'   \item{\code{logprior}}{Numeric vector of log10 binomial prior values,
#'         same length}
#'   \item{\code{theta_mat}}{Numeric matrix of dimension
#'         \eqn{d \times (2^d - 1)}: causal estimate vectors for all models}
#' }
#'
#' @references
#' \insertAllCited{}
#'
#' @export
exhaustive_bf_cpp <- function(XtY, XtX, YtY, sigma_vec, d_Exposure, n_SNPs, prior_prob) {
    .Call(`_MRBMA_exhaustive_bf_cpp`, XtY, XtX, YtY, sigma_vec, d_Exposure, n_SNPs, prior_prob)
}

#' @title Shotgun Stochastic Search (SSS) core in C++ for MRBMA
#' @description Implements the shotgun stochastic search (SSS) algorithm of
#' \insertCite{Hans2007;textual}{MRBMA} as adapted for multivariable MR by \insertCite{Zuber2020;textual}{MRBMA}, entirely in C++,
#' using a \code{std::unordered_map} for O(1)-average memoisation of all visited models. This function is the computational backend of
#' \code{MRBMA_SSS}
#'
#' @param XtY       Numeric vector of length \eqn{d}. Pre-computed
#'                  \eqn{X^\top Y}
#' @param XtX       Numeric matrix of dimension \eqn{d \times d}. Pre-computed
#'                  \eqn{X^\top X}
#' @param YtY       Positive numeric scalar. Pre-computed \eqn{Y^\top Y}
#' @param sigma_vec Numeric vector of length \eqn{d}. Prior standard
#'                  deviations
#' @param d_Exposure      Positive integer. Number of exposures \eqn{d}
#' @param n_SNPs    Positive integer. Number of SNPs (instruments) \eqn{n}
#' @param prior_prob Numeric scalar in \eqn{(0, 1)}. Prior inclusion
#'                  probability per exposure
#' @param kmin      Positive integer \eqn{k_{\min}}. Minimum model size for the
#'                  deterministic phase and the SSS neighbourhood constraint
#' @param kmax      Positive integer \eqn{k_{\max} \leq d}. Maximum model size
#'                  for the SSS neighbourhood constraint
#' @param max_iter  Positive integer. Number of SSS iterations. Ignored if
#'                  \code{kmax == kmin}
#' @param verbose   Logical. If \code{TRUE}, prints progress to \code{Rcout}
#'                  every 1,000 iterations (default \code{false})
#'
#' @details
#' Throughout, \eqn{d} denotes the number of exposures, \eqn{n} the number of
#' SNPs, and \eqn{k = |\gamma|} the current model size (\eqn{k_{\min} \leq k \leq k_{\max}}).
#'
#' Deterministic phase: all models of size \eqn{1, \ldots, k_{\min}} are
#' enumerated and evaluated. Stochastic phase: at each iteration a model is
#' drawn from the current neighbourhood weighted by posterior evidence
#' (\eqn{\propto 10^{\text{logBF} + \text{logprior}}}); its neighbourhood
#' is created by add, delete and swap moves; unvisited neighbours are
#' evaluated and stored in the hash tables; the process repeats. Log-sum-exp
#' rescaling prevents \eqn{10^x} overflow during weighted sampling
#'
#' @return A named list:
#' \describe{
#'   \item{\code{keys}}{Character vector of all visited model keys}
#'   \item{\code{logBF}}{Numeric vector of log10 Bayes Factors (BFs) for visited
#'         models}
#'   \item{\code{logprior}}{Numeric vector of log10 prior values for visited
#'         models}
#'   \item{\code{theta_mat}}{Numeric matrix of dimension \eqn{d \times M},
#'         where \eqn{M} is the total number of visited models: causal
#'         estimate vectors}
#' }
#'
#' @references
#' \insertAllCited{}
#'
#' @export
sss_core_cpp <- function(XtY, XtX, YtY, sigma_vec, d_Exposure, n_SNPs, prior_prob, kmin, kmax, max_iter, verbose = FALSE) {
    .Call(`_MRBMA_sss_core_cpp`, XtY, XtX, YtY, sigma_vec, d_Exposure, n_SNPs, prior_prob, kmin, kmax, max_iter, verbose)
}

